CREATE DATABASE SENAI_PERSONAGEM;

USE SENAI_PERSONAGEM;

CREATE TABLE PERSONAGEM (
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR(250) NOT NULL 
	,DATA_LANCAMENTO DATE NOT NULL 
);

INSERT INTO PERSONAGEM(NOME, DATA_LANCAMENTO)
VALUES('HOMEM ARANHA', '1996/03/05');
INSERT INTO PERSONAGEM(NOME, DATA_LANCAMENTO)
VALUES('REGINEI DAS FLECHA', '1988/08/05');
INSERT INTO PERSONAGEM(NOME, DATA_LANCAMENTO)
VALUES('BATIMINHA', '1980/07/15');
INSERT INTO PERSONAGEM(NOME, DATA_LANCAMENTO)
VALUES('SUPER MOUSE', '1996/10/08');
INSERT INTO PERSONAGEM(NOME, DATA_LANCAMENTO)
VALUES('LINDOMAR SUBZERO BRASILEIRO', '1977/10/10');